name: 'binance_project'
version: '1.0.0'
config-version: 2


profile: 'binance_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  binance_project:
   
    staging:
      +materialized: view
 
    marts:
      +materialized: table